CREATE SEQUENCE IF NOT EXISTS USER_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS ROLE_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS PROJECT_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS PERSON_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS SHOP_SEQ START WITH 1000;
CREATE SEQUENCE IF NOT EXISTS TICKET_SEQ START WITH 1000;